<?php 
	print '
	<h1>Burza i biznis vole Donalda Trumpa, a kako i ne bi?</h1>
	<figure>
		<img src="img/Donald.jpeg" alt="HTML5" title="HTML5">
		<figcaption>Američke korporacije i ulagači vrlo su optimistični nakon porezne reforme koja je stupila na snagu početkom godine, no pojedini analitičari sumnjaju u njene dugotrajnije efekte, kao i u to da će donijeti bolje dane prosječnim zaposlenicima i potrošačima</figcaption>
	</figure>
	<p>Burzovni indeks Dow Jones, koji mjeri puls američke ekonomije, samo u posljednjih mjesec dana postavio je dva rekorda. Prvo je 4. siječnja prvi put u povijesti preskočio razinu od 25.000 bodova, da bi trinaest dana kasnije prvi put premašio i 26.000 bodova. Spomenuti su rekordi samo nastavak vrlo optimističnog trenda koji je započeo izborom Donalda Trumpa za predsjednika Sjedinjenih Američkih Država.</p>
	<p>U posljednjih 14 mjeseci vrijednost Dow Jonesa porasla je za gotovo 50 posto i iako oprezni analitičari upozoravaju da iza svakog razdoblja rasta mora doći i famozna korekcija, ulagački optimizam zasad ne posustaje. Koliko god Trump zaslužio pregršt kritika kojima ga se svakodnevno zasipa, nitko ne sumnja u to da se želi zalagati za američku ekonomiju i da joj želi osigurati sve uvjete za što brži rast u što kraćem razdoblju. Iz takve slike, očekivano, nestaje briga oko dugoročnih posljedica, no burze su očito spremne nagraditi one koji se klade na kratki rok.</p>
	<p>Jedan od dugo najavljivanih i očekivanih poteza koje je još tijekom svoje kampanje najavljivao Trump povučen je nekoliko dana prije kraja 2017., da bi zaživio početkom godine. Riječ je o poreznoj reformi kojoj je glavni cilj u kratkom roku rasteretiti i građane i kompanije i stvoriti uvjete za snažan investicijski zamah koji bi trebao rezultirati čvrstim gospodarskim rastom.</p>
	<p>Iako je od samog izglasavanja reforme i njenog stupanja na snagu već prošlo dovoljno vremena da početna oduševljenost splasne, ovotjedni sastanak Svjetskog gospodarskog foruma u švicarskom Davosu pokazao je da među američkim i svjetskim biznismenima i dalje vlada jak optimizam. Stephen Schwarzman, glavni izvršni direktor investicijske kuće Blackstone Group, izjavio je da očekuje mnogo ulaganja u SAD, što je zaboravljeni i podcijenjeni aspekt američke porezne reforme, piše Bloomberg. Kompanije diljem svijeta sada gledaju prema SAD-u komentirajući da je to mjesto unutar razvijenog svijeta na kojem treba biti, dodao je Schwarzman.</p>
	<p>S njime se slaže i Tidjane Thiam, prvi čovjek velike švicarske investicijske banke Credit Suisse, koji je prokomentirao da će reforma potaknuti kompanije na investicije, dok je Adena Friedman, šefica američke burze NASDAQ, kazala da je reforma poticaj rastu SAD-a. Vjeru u bolju budućnost gaji i Jamie Dimon, prvi čovjek banke JP Morgan Chase koji predviđa da će porezne promjene donijeti rast plaća i ekonomski skok. Mislim da je vjerojatno da ćemo u jednom trenutku ove godine dosegnuti (rast od) četiri posto, izjavio je u Davosu Dimon za američku televizijsku mrežu CNBC.</p>
	<p>No nisu svi toliko optimistični. Frank Appel, glavni izvršni direktor Deutsche Posta, predviđa da će porezna reforma donijeti samo kratkoročne efekte, dok je Brian Moynihan, glavni izvršni direktor Bank of America, podsjetio da američka stopa nezaposlenosti na razini od 4,1 posto znači da je stvarnost povratka radnih mjesta (u SAD, op.a.) vrlo složena te je upitao gdje će ti ljudi raditi.</p>
	<p>O čemu se točno radi? Američka porezna reforma donijela je niz promjena na strani oporezivanja kompanija, ali i na strani oporezivanja stanovnika. Promjene u oporezivanju kompanija puno su značajnije i to posebno stoga što su rezultat dugogodišnjih problema u američkom poreznom sustavu, što je, drže mnogi, smanjivalo konkurentnost američkih korporacija u svijetu. Neke od uvedenih promjena uvedene su kao permanentne dok je dobar dio njih privremen i porezno olakšanje će s godinama biti sve manje.</p>
	<p>Na korporativnoj strani prva velika i vrlo bitna promjena je sniženje porezne stope na dobit kompanija s 35 na 21 posto. Amerika je dugo godina bila jedna od država s najvišom stopom poreza na dobit, što je tamošnje kompanije tjeralo na razne sheme kojima su izbjegavale oštro oporezivanje. Najčešće se radilo o tome da su tamošnje multinacionalne kompanije svu dobit ostvarenu u inozemstvu zadržavale u inozemstvu jer bi prilikom povlačenja te dobiti u SAD ona bila predmetom oporezivanja.</p>
	<p>Druga bitna promjena bavi se upravo tom dobiti koja se nalazi na računima velikih korporacija u inozemstvu. Reformom će se omogućiti privremeno razdoblje u kojem će kompanije po nižoj stopi moći prebaciti zaradu nazad u SAD, a drugi dio reforme je promijenio pravila oporezivanja te dobiti i za ubuduće. Ugrubo, američki poreznici će tjerati američke korporacije da plate porez na dobit u barem nekom određenom iznosu, bez obzira na to kojoj državi plaćaju taj porez.</p>
	<p>Namjera te promjene je da se američke kompanije obeshrabri u pokušajima da svoje poslovanje prebacuju u porezne oaze s gotovo nepostojećim porezima na dobit. Dodatno, u poreznu reformu su ugrađene i mjere koje bi trebale onemogućiti kompanijama da internim transferima i nabijanjem cijena među poslovnim jedinicama unutar same korporacije također umanjuju poreznu obvezu.</p>
		
	<p>Source: <a href="https://www.tportal.hr/biznis/clanak/burza-i-biznis-vole-donalda-trumpa-a-kako-i-ne-bi-foto-20180126" target="_blank">T-Portal</a></p>
	'
?>